// Generated by CoffeeScript 1.12.7
var WorkshopRootApp,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

WorkshopRootApp = (function(superClass) {
  extend(WorkshopRootApp, superClass);

  function WorkshopRootApp() {
    return WorkshopRootApp.__super__.constructor.apply(this, arguments);
  }

  WorkshopRootApp.is_allowed = function() {
    return true;
  };

  WorkshopRootApp.group = function() {
    return "workshop-group";
  };

  WorkshopRootApp.label = function() {
    return "workshop.app.label";
  };

  WorkshopRootApp.isStartApp = function() {
    return false;
  };

  WorkshopRootApp.path = function() {
    return ["workshop-1"];
  };

  WorkshopRootApp.prototype.allow_unload = function() {
    return CUI.confirm({
      text: "Do you want to close the Workshop App?"
    });
  };

  WorkshopRootApp.prototype.unload = function() {
    ez5.rootLayout.empty("center");
    return WorkshopRootApp.__super__.unload.call(this);
  };

  WorkshopRootApp.prototype.load = function() {
    var itemList;
    WorkshopRootApp.__super__.load.call(this);
    this.__plugin = ez5.pluginManager.getPlugin("workshop-example-1");
    itemList = new CUI.ItemList({
      "class": "workshop-example-itemlist",
      items: [
        {
          active: true,
          loca_key: "workshop-example-1.item1",
          onClick: (function(_this) {
            return function() {
              return _this.showSimpleElements();
            };
          })(this)
        }, {
          loca_key: "workshop-example-1.item2",
          onClick: (function(_this) {
            return function() {
              return _this.showTemplate();
            };
          })(this)
        }, {
          loca_key: "workshop-example-1.item3",
          onClick: (function(_this) {
            return function() {
              return _this.showTemplateTwo();
            };
          })(this)
        }, {
          loca_key: "workshop-example-1.item4",
          onClick: (function(_this) {
            return function() {
              return _this.showMap();
            };
          })(this)
        }
      ]
    });
    itemList.render();
    this.__horizontalLayout = new CUI.HorizontalLayout({
      left: {
        "class": "ez5-workshop-hl-left",
        content: itemList
      }
    });
    ez5.rootLayout.replace(this.__horizontalLayout, "center");
    return CUI.resolvedPromise();
  };

  WorkshopRootApp.prototype.showSimpleElements = function() {
    var text, title, verticalListLayout;
    title = new CUI.Label({
      text: "Hello world"
    });
    text = new CUI.Label({
      text: "Lorem Ipsum Dolor Sit amet",
      multiline: true
    });
    verticalListLayout = new CUI.VerticalList({
      "class": "asdadsaas",
      content: [title, text]
    });
    return this.__horizontalLayout.replace(verticalListLayout, "center");
  };

  WorkshopRootApp.prototype.showTemplate = function() {
    var htmlTemplate;
    htmlTemplate = new CUI.Template({
      name: "workshop-template-1"
    });
    return this.__horizontalLayout.replace(htmlTemplate, "center");
  };

  WorkshopRootApp.prototype.showTemplateTwo = function() {
    var htmlTemplate, inputData;
    inputData = {};
    htmlTemplate = new CUI.Template({
      name: "workshop-template-2",
      map: {
        slot1: true,
        slot3: true
      }
    });
    htmlTemplate.map.slot1.append(new CUI.Label({
      text: "Lorem Ipsum"
    }));
    htmlTemplate.map.slot3.append(new CUI.Button({
      text: "A button",
      onClick: function() {
        return CUI.confirm({
          text: "Hello im a button!"
        });
      }
    }));
    return this.__horizontalLayout.replace(htmlTemplate, "center");
  };

  WorkshopRootApp.prototype.showMap = function() {
    var map, staticMarkers;
    staticMarkers = [
      {
        position: {
          lat: 52.520645,
          lng: 13.409779
        },
        cui_onClick: function(ev) {
          return alert(CUI.util.dump(ev.target.options.position));
        }
      }, {
        position: {
          lat: 52.534078,
          lng: 13.410464
        },
        title: 'A',
        cui_onClick: function(ev) {
          return alert(CUI.util.dump(ev.target.options.position));
        }
      }, {
        position: {
          lat: 52.515691,
          lng: 13.387249
        },
        title: 'B',
        cui_onClick: function(ev) {
          return alert(CUI.util.dump(ev.target.options.position));
        }
      }
    ];
    map = new CUI.LeafletMap({
      "class": "workshop-map",
      clickable: false,
      zoomToFitAllMarkersOnInit: true,
      onClick: (function(_this) {
        return function() {
          return console.log("Click");
        };
      })(this),
      onReady: (function(_this) {
        return function() {
          return console.log("Map init");
        };
      })(this)
    });
    map.addMarkers(staticMarkers);
    this.__horizontalLayout.replace(map, "center");
    return this.__searchForGeoObjects().done((function(_this) {
      return function(markers) {
        if (markers && markers.length > 0) {
          return map.addMarkers(markers);
        }
      };
    })(this));
  };

  WorkshopRootApp.prototype.__searchForGeoObjects = function() {
    var column, dfr, i, len, locationFieldByObjecttype, objecttype, objecttypeName, ref, ref1, validObjecttypes;
    dfr = new CUI.Deferred();
    locationFieldByObjecttype = {};
    validObjecttypes = [];
    console.log("Objecttypes with columns data:", ez5.schema.CURRENT._objecttype_by_name);
    ref = ez5.schema.CURRENT._objecttype_by_name;
    for (objecttypeName in ref) {
      objecttype = ref[objecttypeName];
      ref1 = objecttype.columns;
      for (i = 0, len = ref1.length; i < len; i++) {
        column = ref1[i];
        if (column.type === "custom:base.custom-data-type-location.location") {
          if (!locationFieldByObjecttype[objecttypeName]) {
            locationFieldByObjecttype[objecttypeName] = [];
            validObjecttypes.push(objecttypeName);
          }
          locationFieldByObjecttype[objecttypeName].push(column.name);
        }
      }
    }
    console.log(locationFieldByObjecttype);
    ez5.api.search({
      data: {
        debug: "WorkShopDebug"
      },
      json_data: {
        type: "object",
        objecttypes: validObjecttypes,
        format: "long",
        offset: 0,
        limit: 1000,
        search: []
      }
    }).done((function(_this) {
      return function(data) {
        var j, k, len1, len2, location, locationField, locationFields, markers, object, ref2;
        if ((data != null ? data.count : void 0) === 0) {
          dfr.resolve();
        }
        markers = [];
        ref2 = data.objects;
        for (j = 0, len1 = ref2.length; j < len1; j++) {
          object = ref2[j];
          locationFields = locationFieldByObjecttype[object._objecttype];
          for (k = 0, len2 = locationFields.length; k < len2; k++) {
            locationField = locationFields[k];
            location = object[object._objecttype][locationField];
            if (location) {
              markers.push(location.mapPosition);
            }
          }
        }
        return dfr.resolve(markers);
      };
    })(this));
    return dfr.promise();
  };

  return WorkshopRootApp;

})(RootMenuApp);

ez5.session_ready((function(_this) {
  return function() {
    return ez5.rootMenu.registerApp(WorkshopRootApp);
  };
})(this));
