// Generated by CoffeeScript 1.12.7
var WorkshopRootApp,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

WorkshopRootApp = (function(superClass) {
  extend(WorkshopRootApp, superClass);

  function WorkshopRootApp() {
    return WorkshopRootApp.__super__.constructor.apply(this, arguments);
  }

  WorkshopRootApp.is_allowed = function() {
    return true;
  };

  WorkshopRootApp.group = function() {
    return "workshop-group";
  };

  WorkshopRootApp.label = function() {
    return "workshop.app.label";
  };

  WorkshopRootApp.isStartApp = function() {
    return false;
  };

  WorkshopRootApp.path = function() {
    return ["workshop"];
  };

  WorkshopRootApp.prototype.allow_unload = function() {
    return CUI.confirm({
      text: "Do you want to close the Workshop App?"
    });
  };

  WorkshopRootApp.prototype.unload = function() {
    ez5.rootLayout.empty("center");
    return WorkshopRootApp.__super__.unload.call(this);
  };

  WorkshopRootApp.prototype.load = function() {
    var itemList;
    WorkshopRootApp.__super__.load.call(this);
    this.__plugin = ez5.pluginManager.getPlugin("workshop-example-1");
    itemList = new CUI.ItemList({
      "class": "workshop-example-itemlist",
      items: [
        {
          active: true,
          loca_key: "workshop-example-1.item1",
          onClick: (function(_this) {
            return function() {
              return _this.__showSimpleElements();
            };
          })(this)
        }, {
          loca_key: "workshop-example-1.item2",
          onClick: (function(_this) {
            return function() {
              return _this.__showTemplate();
            };
          })(this)
        }, {
          loca_key: "workshop-example-1.item3",
          onClick: (function(_this) {
            return function() {
              return _this.__showTemplateTwo();
            };
          })(this)
        }, {
          loca_key: "workshop-example-1.item4",
          onClick: (function(_this) {
            return function() {
              return _this.__showConfig();
            };
          })(this)
        }
      ]
    });
    itemList.render();
    this.__horizontalLayout = new CUI.HorizontalLayout({
      left: {
        "class": "ez5-workshop-hl-left",
        content: itemList
      }
    });
    ez5.rootLayout.replace(this.__horizontalLayout, "center");
    return CUI.resolvedPromise();
  };

  WorkshopRootApp.prototype.__showSimpleElements = function() {
    var text, title, verticalListLayout;
    title = new CUI.Label({
      text: "Hello world"
    });
    text = new CUI.Label({
      text: "Lorem Ipsum Dolor Sit amet",
      multiline: true
    });
    verticalListLayout = new CUI.VerticalList({
      content: [title, text]
    });
    return this.__horizontalLayout.replace(verticalListLayout, "center");
  };

  WorkshopRootApp.prototype.__showTemplate = function() {
    var htmlTemplate;
    htmlTemplate = new CUI.Template({
      name: "workshop-template-1"
    });
    return this.__horizontalLayout.replace(htmlTemplate, "center");
  };

  WorkshopRootApp.prototype.__showTemplateTwo = function() {
    var htmlTemplate, inputData;
    inputData = {};
    htmlTemplate = new CUI.Template({
      name: "workshop-template-2",
      map: {
        slot1: true,
        slot3: true
      }
    });
    htmlTemplate.map.slot1.append(new CUI.Label({
      text: "Lorem Ipsum"
    }));
    htmlTemplate.map.slot3.append(new CUI.Button({
      text: "A button",
      onClick: function() {
        return CUI.confirm({
          text: "Hello im a button!"
        });
      }
    }));
    return this.__horizontalLayout.replace(htmlTemplate, "center");
  };

  WorkshopRootApp.prototype.__showConfig = function() {
    var config, configDump;
    config = ez5.session.getBaseConfig("plugin", "fylr-plugin-workshop");
    configDump = new CUI.ObjectDumper({
      object: config
    });
    return this.__horizontalLayout.replace(configDump, "center");
  };

  return WorkshopRootApp;

})(RootMenuApp);

ez5.session_ready((function(_this) {
  return function() {
    return ez5.rootMenu.registerApp(WorkshopRootApp);
  };
})(this));
