// Generated by CoffeeScript 1.12.7
var WorkshopCollectionPlugin,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

WorkshopCollectionPlugin = (function(superClass) {
  extend(WorkshopCollectionPlugin, superClass);

  function WorkshopCollectionPlugin() {
    return WorkshopCollectionPlugin.__super__.constructor.apply(this, arguments);
  }

  WorkshopCollectionPlugin.prototype.getCurrentTools = function(collection) {
    var e, exampleOne, exampleTwo, objects, tools;
    try {
      objects = collection.getObjects();
    } catch (error) {
      e = error;
      console.warn("Get Objects fail", e);
    }
    if (!objects || (objects != null ? objects.length : void 0) === 0) {
      return [];
    }
    tools = [];
    exampleOne = new ToolboxTool({
      group: collection.getToolGroup(),
      name: "example-plugin-tool",
      sort: "I:1",
      favorite: true,
      run: (function(_this) {
        return function() {
          return CUI.alert({
            text: $$("example-plugin-tool-msg", {
              object_number: objects.length
            })
          });
        };
      })(this)
    });
    tools.push(exampleOne);
    exampleTwo = new ToolboxTool({
      group: collection.getToolGroup(),
      name: "example-plugin-tool-group",
      sort: "I:2",
      favorite: true,
      tools: [
        new ToolboxTool({
          name: "example-plugin-tool-group-1",
          run: (function(_this) {
            return function() {
              return CUI.alert({
                text: "This is an example of a custom tool inside another tool, you have selected " + objects.length + " objects."
              });
            };
          })(this)
        }), new ToolboxTool({
          name: "example-plugin-tool-group-2",
          run: (function(_this) {
            return function() {
              return _this.__runModalExample(objects);
            };
          })(this)
        })
      ]
    });
    tools.push(exampleTwo);
    return tools;
  };

  WorkshopCollectionPlugin.prototype.__runModalExample = function(objects) {
    var _cancelButton, _modal, _sendButton, getTableContent;
    getTableContent = (function(_this) {
      return function() {
        var collectionObject, i, len, object, table;
        table = new CUI.Table({
          "class": "ez5-metadata-browser-group",
          flex: true,
          key_value: true
        });
        for (i = 0, len = objects.length; i < len; i++) {
          collectionObject = objects[i];
          object = collectionObject.getObject();
          table.addRow({
            key: "UUID",
            value: object._uuid
          });
        }
        return table;
      };
    })(this);
    _cancelButton = new CUI.Button({
      text: "Cancel",
      onClick: (function(_this) {
        return function() {
          return _modal.destroy();
        };
      })(this)
    });
    _sendButton = new CUI.Button({
      text: "Send",
      primary: true,
      onClick: (function(_this) {
        return function() {
          var apiXHR;
          _cancelButton.disable();
          _sendButton.disable();
          apiXHR = new CUI.XHR({
            method: "POST",
            url: "https://run.mocky.io/v3/c61c3f9c-0edf-4eaa-b090-57f9400e42a8"
          });
          return apiXHR.start().done(function(response) {
            var alert;
            alert = new CUI.Alert({
              text: "Server response: " + response.message
            });
            return alert.open().done(function() {
              return _modal.destroy();
            });
          });
        };
      })(this)
    });
    _modal = new CUI.Modal({
      pane: {
        header_left: new LocaLabel({
          loca_key: "example-modal-title"
        }),
        content: [
          new CUI.Label({
            text: "Here is a list of the uuid's of the selected objects:"
          }), getTableContent()
        ],
        footer_right: [_cancelButton, _sendButton]
      }
    });
    return _modal.show();
  };

  return WorkshopCollectionPlugin;

})(CollectionPlugin);

ez5.session_ready(function() {
  return Collection.registerPlugin(new WorkshopCollectionPlugin());
});
